### ISSUE TITLE
QR Code not visible in manager after enabling

### ISSUE THREAD

**Issue by al5040** [Jako/TwoFactorX#4]
Hello Jako,

first of all, thank you very much for the work with this MODX3 extra.

I tested it twice in a new MODX 3.0.5-pl installation. Each time, after activating two-factor authentication in system settings, a window appeared, but it did not show a QR code.

I have attached a screenshot. The window disappears again after a while, but a logout as described does not occur either.

PHP version is 8.3.

In the user profile the QR code is visible as normal.

![Screenshot 2024-05-02 184123](https://github.com/Jako/TwoFactorX/assets/103522299/3970f93c-da98-4ef5-a2ee-1281525e6f9a)

**Comment by al5040** [comment]
I installed MODX3 again and also installed the TwoFactorX extra one more time.

After activating two-factor authentication in system settings, I see the above window again without the QR code.
There is neither an error message in the error logfile (debug mode is on) nor anything noticeable in the network analysis in the Dev Tools in Firefox.

Unfortunately, I don't know how to get MODX to show the window one more time without having to reinstall.

**Comment by smg6511** [comment]
I can confirm this issue as well when testing on 3.1.0-dev / php 8.2.

**Comment by Hylke-sterc** [comment]
We also encounter same issue on MODX 3.0.5 , PHP 8.2.19.

**Comment by Jako** [comment]
This should be fixed with 1.0.7

**Comment by SnowCreative** [comment]
I just installed 1.0.8, and I'm still having this issue.

MODX 2.8.8, PHP 7.4

**Comment by Jako** [comment]
Please look into the PHP error log and post errors that occur in the twofactorx folder here. If there are no errors in this log file: Is the QR Code visible in the user profile TwoFactorX tab?

**Comment by SnowCreative** [comment]
I'm not seeing errors in PHP log. MODX log only does this:

[2025-05-29 13:57:11] (ERROR @ /home/actonwat/modxcore/xpdo/xpdo.class.php : 644) Could not load class: GridContainer from mysql.gridcontainer.

But I think that's probably unrelated. Yes, the QR code is visible in the profile TwoFactorX tab.

**Comment by Jako** [comment]
This should be fixed with 1.1.0

**Comment by SnowCreative** [comment]
Yes, works great now. Thanks.
